-------------------------------------------------------------------------------
Test set: com.evento.evento.EventoApplicationTests
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.384 s <<< FAILURE! - in com.evento.evento.EventoApplicationTests
contextLoads  Time elapsed: 0.002 s  <<< ERROR!
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pacoteRepository' defined in com.evento.evento.repository.PacoteRepository defined in @EnableJpaRepositories declared on JpaRepositoriesRegistrar.EnableJpaRepositoriesConfiguration: Cannot resolve reference to bean 'jpaMappingContext' while setting bean property 'mappingContext'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jpaMappingContext': Invocation of init method failed; nested exception is org.hibernate.AnnotationException: Unknown mappedBy in: com.evento.evento.model.Pacote.historico, referenced property unknown: com.evento.evento.model.HistoricoPacote.historicoPacote
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jpaMappingContext': Invocation of init method failed; nested exception is org.hibernate.AnnotationException: Unknown mappedBy in: com.evento.evento.model.Pacote.historico, referenced property unknown: com.evento.evento.model.HistoricoPacote.historicoPacote
Caused by: org.hibernate.AnnotationException: Unknown mappedBy in: com.evento.evento.model.Pacote.historico, referenced property unknown: com.evento.evento.model.HistoricoPacote.historicoPacote

